remote_theme: IIP-Design/lab-notes

title: GPA/LAB Prettier Config
author: Bureau of Global Public Affairs (GPA) Digital Lab Team
author_homepage: https://github.com/IIP-Design
repository: IIP-Design/prettier-config
description: A shared Prettier configuration conforming to the GPA/LAB style guide.
favicon: /prettier-config/assets/img/favicon.ico
logo: /prettier-config/assets/img/dos_seal.svg
show_downloads: true
show_nav: true

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
